MODULE IntSyntax;

(* Test for error messages generated by incompatible integer types *)

VAR s: SHORTINT; i: INTEGER; l: LONGINT;

BEGIN

  l := l;   (* Good, same types *)
  l := i;   (* Good, LONGINT longer than INTEGER *)
  l := s;   (* Good, LONGINT longer than SHORTINT *)
  i := s;   (* Good, INTEGER longer then SHORTINT *)

  i := l;   (* Bad, INTEGER shorter than LONGINT *)
  s := l;   (* Bad, SHORTINT shorter than LONGINT *)
  i := l;   (* Bad, SHORTINT shorter than INTEGER *)

END IntSyntax.